spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/classifier
    username: classifier
    password: classifier
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs

server:
  port: 8080
